export const SWITCH_THEME = 'SWITCH_THEME'
export const CREATE_TASK = 'CREATE_TASK'
export const TASK_DONE = 'TASK_DONE'
export const TASK_IMPORTANT = 'TASK_IMPORTANT'
export const SORTING = 'SORTING'
export const TASKS_FROM_LS = 'TASKS_FROM_LS'
export const DELETE_TASK = 'DELETE_TASK'